import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#121212",
    paddingTop: 25,
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  searchContainer: {
    marginBottom: 15,
  },
  searchInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#2E2E2E",
    borderRadius: 25,
    paddingHorizontal: 15,
    height: 45,
  },
  searchIcon: {
    marginRight: 10,
  },
  searchInput: {
    flex: 1,
    color: "#FFFFFF",
    fontSize: 16,
  },
  clearButton: {
    padding: 5,
  },
  filtersContainer: {
    marginBottom: 20,
  },
  filtersScrollContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 2,
  },
  filterButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#2E2E2E",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    gap: 5,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  labelFilterButton: {
    minWidth: 80,
    justifyContent: "center",
  },
  businessFilterButton: {
    minWidth: 90,
    justifyContent: "center",
  },
  filterButtonActive: {
    backgroundColor: "#006D77",
    borderColor: "#006D77",
  },
  filterButtonText: {
    color: "#CCCCCC",
    fontSize: 12,
    fontWeight: "500",
  },
  filterButtonTextActive: {
    color: "#FFFFFF",
  },
  clearFiltersButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#4A2C2C",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    gap: 5,
    borderWidth: 1,
    borderColor: "#FF5722",
  },
  clearFiltersButtonText: {
    color: "#FF5722",
    fontSize: 12,
    fontWeight: "500",
  },
  list: {
    paddingBottom: 280,
  },
  item: {
    backgroundColor: "#2E2E2E",
    borderRadius: 15,
    padding: 15,
    marginBottom: 15,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  deletedItem: {
    backgroundColor: "#3D2E2E",
    borderWidth: 1,
    borderColor: "#D9534F",
  },
  itemHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 12,
  },
  nameContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
  },
  name: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "600",
    flex: 1,
    minWidth: 0,
  },
  deletedName: {
    textDecorationLine: "line-through",
    color: "#D9534F",
  },
  labelBadge: {
    backgroundColor: "#006D77",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    alignSelf: "flex-start",
  },
  labelBadgeText: {
    color: "#FFFFFF",
    fontSize: 10,
    fontWeight: "bold",
  },
  businessBadge: {
    backgroundColor: "#9C27B0",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    alignSelf: "flex-start",
  },
  businessBadgeText: {
    color: "#FFFFFF",
    fontSize: 10,
    fontWeight: "bold",
  },
  deletedBadge: {
    backgroundColor: "#D9534F",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    marginLeft: 8,
  },
  deletedBadgeText: {
    color: "#FFFFFF",
    fontSize: 10,
    fontWeight: "bold",
  },
  itemContent: {
    gap: 12,
  },
  quantityContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
  },
  inputGroup: {
    flex: 1,
    alignItems: "center",
  },
  inputLabel: {
    color: "#CCCCCC",
    fontSize: 12,
    marginBottom: 5,
    textAlign: "center",
    fontWeight: "500",
  },
  inputValueContainer: {
    backgroundColor: "#3C3C3C",
    borderRadius: 8,
    padding: 8,
    minWidth: 60,
    alignItems: "center",
  },
  inputValue: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "500",
    textAlign: "center",
  },
  totalsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#444444",
  },
  totalItemText: {
    color: "#4CAF50",
    fontSize: 14,
    fontWeight: "600",
  },
  totalEstimatedItemText: {
    color: "#FFC107",
    fontSize: 14,
    fontWeight: "600",
  },
  actionsContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    gap: 10,
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#3C3C3C",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    flex: 1,
    justifyContent: "center",
    gap: 5,
  },
  deleteActionButton: {
    backgroundColor: "#4A2C2C",
  },
  restoreActionButton: {
    backgroundColor: "#2C4A2C",
  },
  actionButtonText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "500",
  },
  deleteActionButtonText: {
    color: "#D9534F",
  },
  restoreActionButtonText: {
    color: "#4CAF50",
  },
  emptyState: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 60,
  },
  emptyStateTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "600",
    marginTop: 16,
    marginBottom: 8,
  },
  emptyStateSubtitle: {
    color: "#CCCCCC",
    fontSize: 14,
    textAlign: "center",
    lineHeight: 20,
  },
  addButton: {
    position: "absolute",
    bottom: 110,
    right: 20,
    backgroundColor: "#006D77",
    borderRadius: 50,
    width: 56,
    height: 56,
    justifyContent: "center",
    alignItems: "center",
    elevation: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    borderWidth: 2,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  totalContainer: {
    position: "absolute",
    bottom: 180,
    left: 20,
    right: 20,
    backgroundColor: "#2E2E2E",
    borderRadius: 15,
    padding: 15,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  totalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  totalLabel: {
    color: "#CCCCCC",
    fontSize: 14,
    fontWeight: "500",
  },
  totalValue: {
    color: "#4CAF50",
    fontSize: 16,
    fontWeight: "700",
  },
  totalEstimatedValue: {
    color: "#FFC107",
    fontSize: 16,
    fontWeight: "700",
  },
  differenceLabelText: {
    color: "#CCCCCC",
    fontSize: 14,
    fontWeight: "500",
  },
  differenceValue: {
    fontSize: 14,
    fontWeight: "600",
  },
  positiveValue: {
    color: "#FF5722",
  },
  negativeValue: {
    color: "#4CAF50",
  },
  clearAllButton: {
    position: "absolute",
    bottom: 738,
    right: 25,
    backgroundColor: "#D9534F",
    borderRadius: 10,
    width: 30,
    height: 30,
    justifyContent: "center",
    alignItems: "center",
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3.84,
  },
});
